name: CICD Pipeline 

on:
  push:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: runner1  # Ensure this is a valid self-hosted runner label

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Maven and Compile Code
        run: sudo apt update && sudo apt install maven -y && mvn compile

    
  
